name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: db_admin
          POSTGRES_PASSWORD: db_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      db_admin: db_admin
      db_password: db_password
      host: localhost
      port: 5432
      db_name: test_db
      frontend: frontend

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Wait for postgres to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          sleep 1
        done

    - name: Run backend tests
      run: |
        pytest

  frontend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install Node dependencies
      run: npm install

    - name: Run frontend tests
      run: |
        npm run test -- --run

  deploy-backend:
    needs: [backend-tests, frontend-test]

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"
          fly deploy --remote-only

  deploy-frontend:
    needs: deploy-backend

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/app
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm install

      - name: Build frontend with backend URL
        env:
          VITE_BACKEND_URL: https://backend-withered-field-5911.fly.dev
        run: |
          echo "VITE_BACKEND_URL=${VITE_BACKEND_URL}" > .env.production
          npm run build

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/app/dist